#!/bin/bash
# -*- sh -*-

COUCHPOTATO_INI=/root/couchpotato.ini
sed -i s/\$NEWZNAB_URL/$NEWZNAB_URL/ $COUCHPOTATO_INI
sed -i s/\$NEWZNAB_API_KEY/$NEWZNAB_API_KEY/ $COUCHPOTATO_INI
sed -i s/\$API_KEY/$API_KEY/ $COUCHPOTATO_INI
sed -i s/\$SABNZBD_URL/$SABNZBD_URL/ $COUCHPOTATO_INI
sed -i s/\$SABNZBD_API_KEY/$SABNZBD_API_KEY/ $COUCHPOTATO_INI

service couchpotato start
tail -f /root/data/logs/CouchPotato.log
